rock-core/rock-package_set

rock.osdeps
This dependency is required for the planning libaries fd_cedalion and fd_uniform
=> Add dependencies for bzip2

source.yml
Multiagent packages have been moved from github to gitorious. This updates the source definition.
=> Migrate multiagent packages from gitorious to github

source.yml
motion_planning_libraries has been moved to GitHub, just adds the sources. Already tested.
=> Moves motion_planning_libraries lib and module from gitorious to github.

libs.autobuild
This is at least annoying. Slows down bootstrap. Might be bad on a headless system.
Signed-off-by: Martin Zenzes <martin.zenzes@dfki.de>
=> prevent ompl from spawning browser to register

libs.autobuild
Reverts rock-core/rock-package_set#44
This makes no sense. One should add a dependency on 'opencv' (the osdep) instead of explicitely referring to external/opencv (the source package)
=> Revert "added dependency of 'external/aruco' to 'external/opencv'"

libs.autobuild
Aruco should depend on 'opencv', not 'external/opencv'. See #44.
=> Use system dependency opencv for external/aruco

libs.autobuild, orogen.autobuild, source-stable.yml
The motion_planning_libraries integrates planning libraries like OMPL and SBPL
into Rock. Most work has been done on the SBPL part which allows comfortable
path planning on traversability maps regarding the size and the orientation of the system.
In addition movement types like lateral movements or backward turns can be used.
=> Adds motion_planning_libraries to the new release

rock.osdeps
The qwt libs are called qwt5 on Arch Linux.
=> Add arch linux osdep for qwt5

patches/snap_cmake.patch
Fixes CMake integration: add missing header for installation and override the default build targets (all and clean) with corresponding custom targets
=> Fix snap CMake integration

libs.autobuild, orogen.autobuild, source.yml
It aims to rename image_processing to perception. Discussed in the rock-dev mailing list email.
Pros: 
1. To avoid two names:  image_processing (folder) and image-processing (github) -> perception
2. laser filters (e.g. remove an area wrt sensor or body-frame), object recognition and segmentation and ,why not, pcl library (currently is under slam) would have a place in rock.
3. In general everything related to sensing the environment (camera, radar, lidar, tof, etc...) but not building a map.
Cons: 
1. Renaming 
The pull request has two commits:
jhidalgocarrio@24b628eaaf1cd8b2ea307c43c69f248fd50cb147 affect folders and repositories
jhidalgocarrio@dc23a90e23b500f77fb7c290f151f7a8b6db9bed  affects the renaming of the working-group rock-image-processing
This pull request should be done …
=> Rock perception

libs.autobuild
NOTE: this is do-not-merge as I'll need to create the git repository in rock-control first.
Code is here for now:
https://github.com/Brazilian-Institute-of-Robotics/tools-ruby_sdf
=> add control/ruby_sdformat

rock.osdeps
Recently the packages got a sufficient version number (pcl1.7), a backport was made for Ubuntu 14.04, so there is no need to compile the sources on these operating systems.
=> added pcl osdeps for OSes where a package is available

rock.osdeps
Install development packages of graphviz to allow direct library use.
=> Add development packages for graphviz

libs.autobuild
This works on autoproj 1.x becaus add_osdeps_overrides does not
validate the package name, but will fail on autoproj 2.x
=> there are no osdeps called glew and glfw

rock.osdeps-ruby19
In relation to this discussion:
https://github.com/rock-core/rock-package_set/issues/83
and this previous pull request:
https://github.com/rock-core/rock-package_set/pull/85
=> The gem for net-ssh has to be of version <=2.10

libs.autobuild
The pacakge does not build scince weeks becasue a patch could not be applied.
The maintainers does not respond, therefore i remove the package now, to
get the rock-all build passed and the HP generated
=> Removed ceres_solver

libs.autobuild, patches/gmapping.patch, source.yml
the source for gmapping that is used in ROS has some (a lot of) fixes, that are not in the original openslam repo, so adapted source.yml to that. Also changed the patch to remove catkin-related stuff. This time used --no-prefix with git format-patch so default patchlevel -p0 works.
=> changed gmapping source repo, adapted patch

libs.autobuild
otherwise building on jessie fails
Signed-off-by: Martin Zenzes <martin.zenzes@dfki.de>
=> add "-fPIC" flag to libply

rock.osdeps
Some of the other boost libraries implicitely require boost-system
to be installed, which means that the boost-system dependency start
creeping up virtually everywhere in the cmake code.
=> install boost-system when boost is required

libs.autobuild
Avoids occasional build-failures due to parallel building
=> Prevent parallel building of snap

rock.osdeps
left old definitions as they were, but removed the lib names from default (libs are automatically installed by the -dev package)
=> updated osdeps for ubuntu 15.10

libs.autobuild
This uses API that was already present in 1.x, but for which no
deprecation warnings had been issued. 2.x will be pretty verbose
about these, so change the autobuild code to either use the new
APIs, or be compatible with both 1.x and 2.0
=> remove usage of APIs deprecated in autoproj 2.0 in a 1.x-compatible way

libs.autobuild, manifests/slam/gtsam.xml, patches/gtsam.patch, rock.osdeps, source.yml
This PR fixes slam/gtsam update&build with autoproj
It adds the following required os dependencies:
boost-timer:
boost-date-time:
boost-serialization:
metis:
=> gtsam into rock package_set and new boost modules in a separated manner

rock.osdeps
This is **NOT** tested on older ubuntus. Please test before merging.
=> fix vtk dependency for ubuntu 16.04+

libs.autobuild, manifests/planning/ompl.xml, source.yml
Move the planning libraries to the planning folders and provide a valid manifest.
=> Move external/sbpl and external/ompl to planning folder

source.yml
git://git.gnome.org/aravis url is not working anymore.
The github url is taken from the original page:
https://wiki.gnome.org/action/show/Projects/Aravis
=> fixed avaris driver source url

rock.osdeps
python-vtk has a dependency to vtk5 and conflicts with the vtk6 installation
=> when libvtk6 is used, also python-vtk6 should be used

rock.osdeps
On 16.04 libqglviewer-dev installs the qt5 version of qglviewer.
The qt4 version is called libqglviewer-dev-qt4
=> Add correct lib name for libqglviewer on 16.04

rock.osdeps
Provides support for latlong/utm conversions. Will be used by
control/ruby_sdformat to support SDF's spherical_coordinates
element.
=> define ruby-geoutm

rock.osdeps
This should be merged when [#37](https://github.com/rock-core/base-cmake/pull/37) is merged
=> Add gtest and google-mock to rock.osdeps

patches/ompl_pkgconfig.patch, source.yml
This version will require cxx11 and (compared to the previously used version 0.14) and among other changes will use std::shared_ptr instead of boost
=> Use recent version of planning/ompl: 1.2.1

source.yml
New url according to http://www.advancednavigation.com.au/product/spatial#software
The old url does not work anymore: http://www.advancednavigation.com.au/sites/advancednavigation.com.au/files/SpatialSDK.zip
=> Updates the url of drivers/imu_an_spatial

rock.osdeps
With rock-core/drivers-iodrivers_base#20, iodrivers_base test suite would become dependent on GTest (only for the tests). This moves the gtest osdeps from rock to rock.core.
Depends on:
=> Move dependency from GTest to rock.core package set

libs.autobuild, orogen.autobuild
The two packages provide basic GNSS-related functionality -- types that were formerly in the mb500 package, and the conversion-to-UTM
=> add the gps_base packages

rock.osdeps
The qglviewer osdep changed in Debian Stretch. This change should make it future proof.
=> Fix qglviewer osdeps on debian stretch

rock.osdeps
This fixes the gstreamer osdep on Debian Stretch, because it changed since Jessie.
=> Fix gstreamer osdep on debian stretch

patches/apriltags.patch
The current patch leaves out the last closing tag
=> Fix apriltags patch -- otherwise manifest.xml will be invalid

source.yml
svn not available anymore, now from github
(also officially linked from openslam.org homepage)
=> fixed hogman location

libs.autobuild
Beyond the merits of writing custom code to handle a standard package,
*NOTHING* that modifies the filesystem should be ever done in the
prepare method of a package.
=> fix drivers/libusb, drivers/imu_myahrs_plus and drivers/glew to not modify the filesystem in #prepare

patches/ompl.patch, patches/ompl_pkgconfig.patch, source.yml
The patch to install ompl is updated so that flann is linked properly.
=> Fixes link error when building ompl with Flann installed

rock.osdeps
Both are on purpose plugins, that is runtime-only and
not devel packages since GStreamer gives a uniform way
to load and use these plugins.
=> define gstreamer-vaapi and gstreamer-plugins-bad

libs.autobuild
The tests in gui/robot_model is an app for a human to run. Do not let
autoproj believe there is something to run automatically
=> mark gui/robot_model's tests as not available

orogen.autobuild
qt_base provides a component implementation with specific hooks
that are called within the Qt main thread instead of the RTT
thread, to follow Qt's own requirements.
Depends on:
=> define gui/orogen/qt_base

patches/libkdtree++_0.7.1.diff, source.yml
This is the first part for updating Gentoo osdeps. My plan is to send the less involved rock.osdeps updates next, and finally changes involving slam/pcl, and how that package is responsible for setting the PKG_CONFIG_PATH for the install directory. Let me know if you want this handled in a different way.
=> update fetch instructions for external/kdtree

rock.osdeps
The OSG 3.4 packages include the plugin, so there's no need
to build it separately.
=> do not build collada_osg on Ubuntu 20.04

patches/orocos_kdl_eigen_v3.patch, source.yml
Due to recent changes of the CMakeLists.txt in the [orocos repo](https://github.com/orocos/orocos_kinematics_dynamics/commit/228754b67123f9568cb21998ec1bebaae7e46ddb#diff-afd1f68b101d292e1f61c6b8dab773ae) the orocos_kdl_eigen patch required an update.
=> Update eigen3 patch. Account for cmake changes in orocos_kdl.

libs.autobuild
Testing for the upcoming debian package release exposed a missing environment setting for gui/robot_model:
```
Traceback (most recent call last):
5: from /opt/rock/master-20.06/rock-master-20.06-gui-robot-model/bin/rock-roboviz:197:in `<main>'
4: from /opt/rock/master-20.06/rock-master-20.06-ruby-gui-vizkit/lib/ruby/vendor_ruby/vizkit/plugin_accessor.rb:40:in `block in add_plugin_spec'
3: from /opt/rock/master-20.06/rock-master-20.06-ruby-gui-vizkit/lib/ruby/vendor_ruby/vizkit/uiloader.rb:341:in `create_plugin'
2: from /opt/rock/master-20.06/rock-master-20.06-ruby-gui-vizkit/lib/ruby/vendor_ruby/vizkit/plugin.rb:549:in `create_plugin'
1: from /opt/rock/master-20.06/rock-master-20.06-ruby-gui-vizkit/lib/ruby/vendor_ruby/vizkit/uiloader.rb:46:in `block in register_3d_plugin' …
```
=> gui/robot_model: fix setting of VIZKIT_PLUGIN_RUBY_PATH

source.yml
Switch to 4.1rc, since 4.0.0-alpha1 did not built due to missing includes
=> slam/gtsam: update to github repository and switch to 4.1rc

rock.osdeps
The library named above is not available in Ubuntu 20.04 anymore and is not provided via the qt4 backports.
=> Remove libqwt5-qt4-dev for Ubuntu 20.04

rock.osdeps
`WARN: osdeps definition for qwt5, previously defined in /home/user/rock/autoproj/remotes/rock.core/rock.osdeps overridden by /home/user/rock/autoproj/remotes/rock/rock.osdeps`
The qwt5 osdep is defined in multiple package sets. I would suggest to remove it here and consolidate it with the definition in the core package set.
=> Remove qwt5 osdep as it is already defined in rock-package_set

rock.osdeps, rock.osdeps-python2, rock.osdeps-python3
Cython definition for python2 will be moved to rock.core package set for consistency reasons
=> Organize python osdeps in version specific files

manifests/slam/g2o.xml, manifests/slam/octomap.xml, rock.osdeps
mark it nonexistent instead making it qt5 to make in impossible to link different qt versions when using the ppa.
It is only used optionally in slam/g2o and slam/octomap so make those deps optional (extra viz tools)
=> libqglviewer-dev-qt4 is not available in 20.04 (even with rock-core ppa)

source.yml
=> Checkout kdl with submodules.

manifests/drivers/imu_an_spatial.xml, source.yml
The [old URL](https://www.advancednavigation.com/sites/default/files/product_software/spatialsdk.zip) for importing the driver imu_an_spatial doesn't work anymore. I have updated the new URL in `source.yml`: https://www.advancednavigation.com/wp-content/uploads/2021/08/spatialsdk.zip
Please merge the pull request to update the link.
=> updated the url for drivers-imu_an_spatial

orogen.autobuild
This package defines components that provide some useful transformations.
They are not defined in drivers/orogen/transformer because they actually
require drivrs/orogen/transformer to be installed (for its orogen plugin)
=> feat: define drivers/orogen/transforms

libs.autobuild, patches/udt_cmakelists.patch, rock.osdeps, source.yml
Update to the gentoo osdeps entries, addition of udt as optionally external package (since at least gentoo does not have it). @doudou please merge if acceptable.
=> Gentoo osdeps

source.yml
The package planning/fast_downward starts to require c++-20 with commit [c9d36f76](https://github.com/aibasel/downward/commit/c9d36f76cdc9ad5757f32a0b4ef79e4ec0c54505). Last "good" is [fe473a20](https://github.com/aibasel/downward/commit/fe473a2011c84f9082068a30fae8653e3823ea7f). Ubuntu 20.04 by default installs gcc-9(which lacks c++-20 support) by default, but can install gcc-10(which would support c++-20). ubuntu-18.04 only installs up to gcc-8. This PR to pins planning/fast_downward at fe473a20. That can be changed again once gcc-10 is installed by default on ubuntu 20.04 or 22.04 becomes usable.
=> Pin planning/fast_downward to one commit before they require c++20

libs.autobuild, source.yml
Add the "hiredis" redis database client. (Used for the database version of the slam3d package)
=> add hiredis database connector

libs.autobuild
Deprecated according to https://github.com/rock-core/autoproj/blob/master/lib/autoproj/autobuild_extensions/dsl.rb#L453
Indirectly, this also fixes:
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
=> Replace deprecated Autoproj.configuration_option by Autoproj.config.declare

patches/gecode.patch
The gist/flatzinc libraries are used by planning/templ, which tries to link against qt4, so either tools/gecode must compile for qt4 or planning/templ(and its reverse dependencies!) must compile against the newest qt available, like gecode does.
This was exposed by the base/cmake change to use target style qt dependencies(Qt4::QtCore etc.).
=> tools/gecode: disable finding qt versions other than 4

init.rb
=> Use File.exist instead of File.exists
