rock-core/rock-package_set

source.yml
Set 'github' as source instead of gitorious. Also adjusted to new naming scheme.
=> Adjustes source.yml in order to point to github instead of gitorious

patches/randward.patch
Otherwise my clang failes (seems double added with whitespaces)
=> randward: Cleanly check for compiler features

patches/tinyxml_cmake.patch
include($ENV{ROCK_CMAKE_MACROS}/Rock.cmake) did not work, so changed to find_package(Rock)
=> update tinyxml_cmake.patch to use find_package(Rock) macro

libs.autobuild, source.yml
include control/sdformat to libs.autobuild
include control/format to source.yaml
=> include control/sdformat package

libs.autobuild, orogen.autobuild, patches/apriltags.patch, source.yml
Add apriltags component to the rock-core package_set. 
The library is directlty downloaded from the developer web page and the orogen component is already in the rock-perception repository.
=> Add apriltags library and orogen component.

libs.autobuild
=> fix installing osg-collada on autoproj 1.x

libs.autobuild, orogen.autobuild
The git rock-gui/gui-vizkit3d_pcl needs to be created, I don't have rights to rock-gui. Thanks.
=> added pcl pointcloud export and vizkit plugin

libs.autobuild, patches/visp.patch, source.yml
Visp is an Open source visual servoing platform library developed by Inria Lagadic team.
visp.inria.fr/
=> Add visp package set

libs.autobuild, manifests/slam/gtsam.xml, patches/gtsam.patch, source.yml
This PR add the gtsam library into the rock package_set
=> libs: gtsam library

libs.autobuild, orogen.autobuild
Allows to find next best exploration poses on a traversability map. Several weighted factors 
are used to specify the exploration behaviour.
Has been used and tested on many different systems.
=> Adds exploration library and module.

source.yml
The current URL is no more available.
=> fix apriltags url

libs.autobuild, orogen.autobuild
=> Add uwv_dynamic_model library and orogen to the package set

libs.autobuild, manifests/slam/g2o.xml, patches/g2o_build4.patch
Adds the manifest file with the updated list of (optional) dependencies
=> Update manifest for slam/g2o

patches/gtsam.patch, source.yml
source: gtsam library to checkout v4.0 by default.
=> gtsam library v4.0

libs.autobuild, orogen.autobuild, source.yml
=> moved iodrivers_base to rock-core

libs.autobuild, orogen.autobuild
Would that be OK with you @maltewi ?
=> add the robot_frames package

source.yml
=> Fix slam/flann archive url

patches/collada.patch, source.yml
Also fix C++11/14 warnings about auto_ptr
=> fix compilation of collada_dom on 18.04

rock.osdeps
Should be merged with https://github.com/rock-core/package_set/pull/138
=> Move Python to rock's main package set

libs.autobuild, orogen.autobuild
The two packages aim at being a collection of packages to do some specific but generally useful stuff with joints.
=> add the joint_tools library and orogen packages

source.yml
Fix the URL to download gazebo package.
=> Fix URL to download ignition-math2.

libs.autobuild, orogen.autobuild
=> add drivers/canopen_master and drivers/orogen/canopen_master

libs.autobuild, source.yml
This adds the vizkit3d debug drawings
=> Add Vizkit3d_Debug_drawings

.travis.yml, libs.autobuild, source.yml
Add latest version of Gecode see https://www.gecode.org (generic constraint development environment)
=> Add tools/gecode package

libs.autobuild, source.yml
=> Add tools/qxcfg

libs.autobuild
=> Activate python extension in tools/graph_analysis

.ci/autoproj-config.yml, patches/gexf_cmake.patch
Fix cxx standard requirements for external/gexf
=> Update  external/gexf

libs.autobuild, source.yml
This seasocks will be used later in https://github.com/rock-drivers/drivers-orogen-controldev_websocket/
=> Add seasocks, a tiny embeddable C++ HTTP and WebSocket server.

orogen.autobuild, rock.osdeps
=> Update  drivers/orogen/controldev_websocket

libs.autobuild
=> Add library control/joint_control_base

libs.autobuild
=> tools/gecode: set configureflags to include building of gist

libs.autobuild, patches/fast_downward.patch, source.yml
Update the source definition for fast downward and enable out of source installation, since they moved to github
=> planning/fast_downward: switch to using github repository

libs.autobuild, rock.osdeps
=> Update missing dependencies

libs.autobuild
=> knowledge_reasoning/owlapi: add setting of OWLAPI_ONTOLOGIES_PATH

libs.autobuild
=> Add knowledge_reasoning/moreorg

rock.osdeps
https://github.com/rock-drivers/drivers-video_capture_vlc/pull/4
=> add harfbuzz and freetype dependencies

source.yml
see: https://github.com/rock-core/autoproj/issues/321
=> delete branch setting in override of planning/ompl

rock.osdeps
Adds the muparser dependency, but also contains a commit which sorts the existing set of osdeps.
=> Add osdeps muparser

patches/g2o_build4.patch
Fixes the export of pkgconfig libraries for g2o.
=> Fix g2o pkgconfig exports

rock.osdeps, rock.osdeps-python2, rock.osdeps-python3
Adds/updates osdeps for gentoo
=> Add gentoo osdeps

manifests/slam/g2o.xml, manifests/slam/octomap.xml, patches/aruco_3.1.x_opencv4.patch, rock.osdeps, source.yml
Update of library versions and deps for supporting Ubuntu20.04
=> Ubuntu20.04 support

libs.autobuild, orogen.autobuild, source.yml
=> Added slam3d and dependencies.

rock.osdeps
=> Mark soqt5 as nonexistent for 18.04

patches/gecode.patch
there was some debugging msg and some workspace failing due to not able to find qt5 .
=> fix issues in gecode patch

libs.autobuild
The package is found in our internal package set and can be moved to the rock core.
=> Add sbpl_spline_primitives library
